Vagrant.configure("2") do |config|
    os = "centos/7"
    net = "192.168.234"
    config.vm.define :dockerhost do |dconfig|
        dconfig.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 1
            vb.name = "docker-host"
        end
        dconfig.vm.hostname = "dockerhost"
        dconfig.vm.box = "#{os}"
        dconfig.vm.network "forwarded_port", guest: "22", host: "2022"
        dconfig.vm.network "private_network", ip: "#{net}.10"
        dconfig.vm.network "public_network"
        dconfig.vm.provision "shell", inline: <<-SHELL
        yum -y update
        SHELL
    end
end