Vagrant.configure("2") do |config|

    os = "centos/7"
    net = "192.168.111"
    config.vm.define :proxy do |proxy_config|
        proxy_config.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = 1
            vb.name = "btw_proxy"
        end
        proxy_config.vm.host_name = 'proxy'
        proxy_config.vm.box = "#{os}"
        proxy_config.vm.network "forwarded_port", guest: 80, host: 8080
        proxy_config.vm.network "private_network", ip: "#{net}.1"
        proxy_config.vm.network "public_network"
        proxy_config.vm.provision "shell", inline: <<-SHELL
        yum -y update
        SHELL
    end
    config.vm.define :web do |web_config|
        web_config.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = 1
            vb.name = "btw_web"
        end
        web_config.vm.host_name = 'web'
        web_config.vm.box = "#{os}"
        web_config.vm.network "private_network", ip: "#{net}.2"
        web_config.vm.network "public_network"
        web_config.vm.provision "shell", inline: <<-SHELL
        yum -y update
        yum install -y git
        SHELL
    end
end
